package com.rpd.roleplaydunyasi;

import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity {
    int bg=Color.rgb(8,9,12), surface=Color.rgb(18,21,27), surface2=Color.rgb(25,29,37), text=Color.rgb(245,247,250), muted=Color.rgb(155,163,176), accent=Color.rgb(139,92,246), cyan=Color.rgb(34,211,238);
    LinearLayout content; TextView header;
    int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} 
    TextView tv(String s,float size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(dp(2),dp(2),dp(2),dp(2));return t;}
    GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    @Override public void onCreate(Bundle b){super.onCreate(b);showShell();home();}
    void showShell(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg); 
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(18),dp(14),dp(18),dp(8));
        header=tv("R.P.D.",25,text);header.setTypeface(Typeface.DEFAULT,Typeface.BOLD);top.addView(header,new LinearLayout.LayoutParams(0,dp(54),1));
        TextView bell=tv("◉",18,text);top.addView(bell,new LinearLayout.LayoutParams(dp(45),dp(50)));root.addView(top);
        content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(16),dp(4),dp(16),dp(12));ScrollView scroll=new ScrollView(this);scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(surface);String[] names={"⌂\nAna","⌕\nKeşfet","＋\nGruplar","✉\nMesaj","●\nProfil"};
        for(int i=0;i<5;i++){Button x=new Button(this);x.setText(names[i]);x.setTextSize(11);x.setTextColor(text);x.setAllCaps(false);final int n=i;x.setOnClickListener(v->{if(n==0)home();if(n==1)discover();if(n==2)groups();if(n==3)messages();if(n==4)profile();});nav.addView(x,new LinearLayout.LayoutParams(0,dp(66),1));}root.addView(nav);setContentView(root);
    }
    void title(String a,String b){content.removeAllViews();TextView h=tv(a,27,text);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(h);content.addView(tv(b,14,muted));}
    void card(String head,String body,String action,View.OnClickListener click){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(17),dp(15),dp(17),dp(15));c.setBackground(bg(surface,18));TextView h=tv(head,18,text);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(h);TextView b=tv(body,14,muted);b.setPadding(0,dp(8),0,dp(10));c.addView(b);if(action!=null){Button z=new Button(this);z.setText(action);z.setTextColor(text);z.setAllCaps(false);z.setOnClickListener(click);c.addView(z);}LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(10),0,0);content.addView(c,p);}
    void chip(String s){TextView c=tv(s,12,text);c.setPadding(dp(12),dp(7),dp(12),dp(7));c.setBackground(bg(surface2,40));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.setMargins(0,dp(8),dp(8),0);content.addView(c,p);}
    void home(){title("Ana Sayfa","Role Play Dünyası");LinearLayout row=new LinearLayout(this);row.addView(tv("Senin akışın",16,text),new LinearLayout.LayoutParams(0,dp(40),1));Button post=new Button(this);post.setText("＋ Gönderi");post.setAllCaps(false);post.setOnClickListener(v->Toast.makeText(this,"Gönderi oluşturma ekranı sonraki sürümde aktif olacak.",Toast.LENGTH_SHORT).show());row.addView(post);content.addView(row);card("Han Karaca  ·  @han","Mafia RP\nYeni hikâye başladı. #mafya #rp","♥ 24    Yorum 8    Kaydet",v->{});card("Komutan Aras  ·  @aras","Askeri RP\nKarakter günlüğü — 2 saat önce. #askeri #rp","♥ 41    Yorum 12    Paylaş",v->{});card("Öne çıkanlar","Toplulukların ve karakterlerin son paylaşımları burada görünecek.","Keşfet",v->discover());}
    void discover(){title("Keşfet","İnsanlar, karakterler, gruplar ve etiketler");card("🔎 Arama","Kullanıcı, karakter, grup veya #hashtag ara.","Ara",v->{});chip("#rp");chip("#mafya");chip("#askeri");chip("#fantastik");chip("#okul");card("Önerilen karakter","Han Karaca\n@han · Mafia RP","Profili Aç",v->profile());card("Popüler topluluk","Çakırbeyli Ailesi · 128 üye","Gruba Git",v->groups());}
    void groups(){title("Gruplar","Aileler, takımlar ve RP toplulukları");card("＋ Yeni Grup","Kendi RP aileni, takımını veya topluluğunu oluştur.","Grup Oluştur",v->groupCreate());card("Çakırbeyli Ailesi","Mafia RP · 128 üye\nDuyurular · RP odaları · Kurallar","Gruba Git",v->{});card("İstanbul Özel Harekât","Askeri RP · 64 üye","Gruba Git",v->{});}
    void groupCreate(){title("Yeni Grup","Topluluğunu oluştur");EditText n=new EditText(this);n.setHint("Grup adı");n.setTextColor(text);n.setHintTextColor(muted);content.addView(n);EditText d=new EditText(this);d.setHint("Açıklama");d.setTextColor(text);d.setHintTextColor(muted);content.addView(d);Button b=new Button(this);b.setText("Grubu Oluştur");b.setAllCaps(false);b.setOnClickListener(v->{Toast.makeText(this,"Grup taslağı oluşturuldu.",Toast.LENGTH_SHORT).show();groups();});content.addView(b);}
    void messages(){title("Mesajlar","Sohbetlerin");card("Han Karaca","Yeni RP odası açıldı.","Sohbete Git",v->{});card("Çakırbeyli Ailesi","Grup sohbeti · 3 yeni mesaj","Aç",v->{});card("RP Odaları","Yakında canlı RP odaları ve istekler burada.","Detay",v->{});}
    void profile(){title("Profil","@han");card("Han Karaca","2 RP karakteri · 128 takipçi\nUzun bio, müzik ve öne çıkan anılar.","Profili Düzenle",v->editProfile());card("🎭 Karakterler","Han Karaca · Mafia RP\nKomutan Aras · Askeri RP","Karakterleri Yönet",v->characters());card("🎨 Görünüm","Siyah-metal · Neon · Pastel · Galaksi","Tema Seç",v->Toast.makeText(this,"Tema seçenekleri hazır.",Toast.LENGTH_SHORT).show());}
    void editProfile(){title("Profili Düzenle","Görünen ad ve bio");EditText n=new EditText(this);n.setHint("Görünen ad");n.setTextColor(text);content.addView(n);EditText bio=new EditText(this);bio.setHint("Bio");bio.setMinLines(4);bio.setTextColor(text);content.addView(bio);Button b=new Button(this);b.setText("Kaydet");b.setAllCaps(false);b.setOnClickListener(v->{Toast.makeText(this,"Profil kaydedildi.",Toast.LENGTH_SHORT).show();profile();});content.addView(b);}
    void characters(){title("RP Karakterleri","Hesabındaki karakterler");card("Han Karaca","Mafia RP · 27 yaş\nGeçmiş, ilişki ağı, etiketler ve tema.","Düzenle",v->{});card("Komutan Aras","Askeri RP · 31 yaş\nGeçmiş, rütbe, ilişkiler ve karakter müziği.","Düzenle",v->{});card("＋ Yeni Karakter","Bir hesaba birden fazla RP karakteri ekleyebilirsin.","Karakter Oluştur",v->Toast.makeText(this,"Karakter oluşturma hazır.",Toast.LENGTH_SHORT).show());}
}
