name: Build RPD APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu al
        uses: actions/checkout@v5

      - name: Java 17 kur
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

       
    

      - name: SDK paketlerini kur
        run: run: yes | run: |
  yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Gradle kur
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10.2'

      - name: APK oluştur
        run: gradle assembleDebug --no-daemon

      - name: APK'yi yükle
        uses: actions/upload-artifact@v4
        with:
          name: RPD-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
